### ISSUE TITLE
Missing details to create an initial Adjacency Matrix file

### ISSUE THREAD

**Issue by Madhavi96** [SYSU-Workflow-Lab/DeepScaler#6]
When training the model (AdapGLA), it requires an adjacency_matrix to be present at the path: _data/dataset/adj_mx_distance.npy_`. 
This is set in the training configurations [config](https://github.com/SYSU-Workflow-Lab/DeepScaler/tree/main/config) as below.

```
AdapGLA:
  num_block: 2
  kernel_size: 5
  num_cheb_filter: 128
  num_time_filter: 128
  conv_type: cheb
  K: 3
  init_feature_num: 64
  adj_mx_path: data/dataset/adj_mx_distance.npy

```
However, in the README file or in the source code, I could not find a place where it mentions how to generate this adjacency_matrix.

In the DeepScaler paper, it mentions, _The initial A contains an invocation relationship between microservices automatically constructed by a distributed tracing tool_. I have deployed the train-ticket application with Jaeger, and does this mean, I have to manually check the traces to build the initial invocation matrix?

It would be really great if an author @ssJokerss, @SYSU-Workflow-Administrator  @mengchy could mention how to do this, since it is not possible to replicate the model training process without this.
